# https://sergiodxa.com/articles/github-actions-npm-publish

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'chore: release v')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "The job commit message ${{ github.event.head_commit.message }}."
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        CI: true
    - run: npm run build --if-present
